/*
 * Copyright (c) Mirth Corporation. All rights reserved.
 * 
 * http://www.mirthcorp.com
 * 
 * The software in this package is published under the terms of the MPL license a copy of which has
 * been included with this distribution in the LICENSE.txt file.
 */

package com.mirth.connect.client.ui;

import java.awt.Dimension;
import java.awt.Point;
import java.util.Calendar;

import com.mirth.connect.client.ui.util.DisplayUtil;

/** Creates the About Mirth dialog. The content is loaded from about.txt. */
public class AboutMirth extends MirthDialog {

    private Frame parent;

    /** Creates new form AboutMirth */
    public AboutMirth() {
        super(PlatformUI.MIRTH_FRAME);
        this.parent = PlatformUI.MIRTH_FRAME;
        initComponents();
        loadContent();
        aboutContent.setCaretPosition(0);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        DisplayUtil.setResizable(this, false);
        setModal(true);
        pack();

        // If this is being called from the LoginPanel, parent may be null
        if (parent == null) {
            setLocationRelativeTo(null);
        } else {
            Dimension dlgSize = getPreferredSize();
            Dimension frmSize = parent.getSize();
            Point loc = parent.getLocation();

            if ((frmSize.width == 0 && frmSize.height == 0) || (loc.x == 0 && loc.y == 0)) {
                setLocationRelativeTo(null);
            } else {
                setLocation((frmSize.width - dlgSize.width) / 2 + loc.x, (frmSize.height - dlgSize.height) / 2 + loc.y);
            }
        }

        setVisible(true);
    }

    /** Loads the contents of about.txt */
    public void loadContent() {
        StringBuilder content = new StringBuilder();

        if (PlatformUI.SERVER_VERSION != null) {
            content.append(Messages.getString("AboutMirth.0") + PlatformUI.SERVER_VERSION + Messages.getString("AboutMirth.1")); //$NON-NLS-1$ //$NON-NLS-2$
        }

        if (PlatformUI.BUILD_DATE != null) {
            content.append(Messages.getString("AboutMirth.2") + PlatformUI.BUILD_DATE + Messages.getString("AboutMirth.3")); //$NON-NLS-1$ //$NON-NLS-2$
        }

        if (PlatformUI.SERVER_ID != null) {
            content.append(Messages.getString("AboutMirth.4") + PlatformUI.SERVER_ID + Messages.getString("AboutMirth.5")); //$NON-NLS-1$ //$NON-NLS-2$
        }

        content.append(Messages.getString("AboutMirth.6") + System.getProperty(Messages.getString("AboutMirth.7")) + Messages.getString("AboutMirth.8")); //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$

        content.append(Messages.getString("AboutMirth.9") + Calendar.getInstance().get(Calendar.YEAR) + Messages.getString("AboutMirth.10")); //$NON-NLS-1$ //$NON-NLS-2$
        content.append(Messages.getString("AboutMirth.11")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.12")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.13")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.14")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.15")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.16")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.17")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.18")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.19")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.20")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.21")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.22")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.23")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.24")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.25")); //$NON-NLS-1$
        content.append(Messages.getString("AboutMirth.26")); //$NON-NLS-1$

        aboutContent.setText(content.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc=" Generated Code
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // @formatter:off
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aboutContent = new javax.swing.JTextPane();
        mirthHeadingPanel1 = new com.mirth.connect.client.ui.MirthHeadingPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(Messages.getString("AboutMirth.27")); //$NON-NLS-1$

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        aboutContent.setEditable(false);
        jScrollPane1.setViewportView(aboutContent);

        jLabel2.setFont(new java.awt.Font(Messages.getString("AboutMirth.28"), 1, 18)); // NOI18N //$NON-NLS-1$
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText(Messages.getString("AboutMirth.29")); //$NON-NLS-1$

        javax.swing.GroupLayout mirthHeadingPanel1Layout = new javax.swing.GroupLayout(mirthHeadingPanel1);
        mirthHeadingPanel1.setLayout(mirthHeadingPanel1Layout);
        mirthHeadingPanel1Layout.setHorizontalGroup(
            mirthHeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mirthHeadingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        mirthHeadingPanel1Layout.setVerticalGroup(
            mirthHeadingPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mirthHeadingPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
                .addContainerGap())
        );

        jButton1.setText(Messages.getString("AboutMirth.30")); //$NON-NLS-1$
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mirthHeadingPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(309, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(mirthHeadingPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // @formatter:on

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt)// GEN-FIRST:event_jButton1ActionPerformed
    {// GEN-HEADEREND:event_jButton1ActionPerformed
        this.dispose();
    }// GEN-LAST:event_jButton1ActionPerformed
     // Variables declaration - do not modify//GEN-BEGIN:variables

    private javax.swing.JTextPane aboutContent;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private com.mirth.connect.client.ui.MirthHeadingPanel mirthHeadingPanel1;
    // End of variables declaration//GEN-END:variables
}
